<script setup>
// GENERATED by tools/build-distributions.mjs — do not edit by hand.
//
// The wall: every product that passed the Kubernetes v1.34 conformance suite,
// from cncf/k8s-conformance. Meant to be looked at, not read.
//
// 131 products certified. 78 logos shown — some vendors file one
// submission per cloud or per variant and the identical marks are deduped. The
// 39 without a usable logo URL are listed by name, so the wall stays complete
// rather than quietly dropping part of the field.
const asset = file => `${import.meta.env.BASE_URL}logos/distros/${file}`

const LOGOS = [
  { slug: 'aks-engine-azurestack', name: 'AKS Engine for Azure Stack' },
  { slug: 'acp', name: 'Alauda Container Platform (ACP)' },
  { slug: 'alicloud', name: 'Alibaba Cloud ACK' },
  { slug: 'eks', name: 'Amazon EKS' },
  { slug: 'eks-d', name: 'Amazon EKS-D' },
  { slug: 'aks', name: 'Azure Kubernetes Service AKS' },
  { slug: 'ck8s', name: 'Canonical Kubernetes' },
  { slug: 'cdk', name: 'Charmed Kubernetes' },
  { slug: 'civo', name: 'Civo Kubernetes' },
  { slug: 'cke', name: 'CKE - Cybozu Kubernetes Engine' },
  { slug: 'ClushKube', name: 'Clush Kube' },
  { slug: 'acornsoft-cocktail', name: 'Cocktail Cloud' },
  { slug: 'controlplane', name: 'Control Plane Managed Kubernetes' },
  { slug: 'Coredge', name: 'Coredge Kubernetes Platform' },
  { slug: 'cozystack', name: 'Cozystack' },
  { slug: 'cubex', name: 'CubeX' },
  { slug: 'daocloud', name: 'DaoCloud Enterprise' },
  { slug: 'dg-i', name: 'DG-i Kubernetes Platform' },
  { slug: 'digitalocean', name: 'DigitalOcean Kubernetes' },
  { slug: 'elastx', name: 'ELASTX Private Kubernetes' },
  { slug: 'exoscale', name: 'Exoscale Scalable Kubernetes Service' },
  { slug: 'gardener-aws', name: 'Gardener on AWS' },
  { slug: 'sap-cp-aws', name: 'Gardener on AWS' },
  { slug: 'gcore', name: 'Gcore Managed Kubernetes' },
  { slug: 'GTCP', name: 'GienTech Container Cloud Platform (GTCP)' },
  { slug: 'gke', name: 'Google Kubernetes Engine' },
  { slug: 'hikube', name: 'Hikube' },
  { slug: 'hpe-ere', name: 'HPE Ezmeral Runtime Enterprise' },
  { slug: 'hpe-kubernetes-service', name: 'HPE’s enterprise Kubernetes platform (HKS)' },
  { slug: 'huawei-cce', name: 'HUAWEI CLOUD Cloud Container Engine' },
  { slug: 'iks', name: 'IBM Cloud Kubernetes Service' },
  { slug: 'Softbank', name: 'Infrinia AI Cloud OS' },
  { slug: 'ionos-cloud', name: 'IONOS Cloud Managed Kubernetes' },
  { slug: 'k0s', name: 'k0s' },
  { slug: 'k3k', name: 'k3k' },
  { slug: 'k3s', name: 'k3s' },
  { slug: 'kubekey', name: 'kubekey' },
  { slug: 'kubeone', name: 'KubeOne' },
  { slug: 'kubeops', name: 'KubeOps' },
  { slug: 'kubermatic', name: 'Kubermatic Kubernetes Platform' },
  { slug: 'k8s-tew', name: 'Kubernetes - The Easier Way' },
  { slug: 'kubespray', name: 'kubespray' },
  { slug: 'kublr', name: 'Kublr' },
  { slug: 'replicated', name: 'kURL' },
  { slug: 'cyso', name: 'Managed Kubernetes' },
  { slug: 'giantswarm-aws', name: 'Managed Kubernetes on aws' },
  { slug: 'nebius', name: 'Managed Service for Kubernetes' },
  { slug: 'metakube-openstack', name: 'MetaKube' },
  { slug: 'metalstackcloud', name: 'Metal Stack Cloud Kubernetes' },
  { slug: 'microk8s', name: 'MicroK8s' },
  { slug: 'mirantis-kubernetes-engine', name: 'Mirantis Kubernetes Engine' },
  { slug: 'nks', name: 'NHN Kubernetes Service NKS' },
  { slug: 'konvoy', name: 'NKP' },
  { slug: 'openFuyao', name: 'openFuyao' },
  { slug: 'OneKS', name: 'OpenNebula Elastic Kubernetes Service (OneKS)' },
  { slug: 'spectrocloud', name: 'Palette' },
  { slug: 'QKE', name: 'QingCloud Kubernetes Engine (QKE)' },
  { slug: 'rafay', name: 'Rafay' },
  { slug: 'rancher', name: 'Rancher Kubernetes' },
  { slug: 'rh-device-edge', name: 'Red Hat build of MicroShift' },
  { slug: 'ibm-openshift', name: 'Red Hat OpenShift on IBM Cloud' },
  { slug: 'rke-government', name: 'RKE Government' },
  { slug: 'scaleway', name: 'Scaleway Kubernetes Kapsule' },
  { slug: 'shturval', name: 'Shturval' },
  { slug: 'sighup-distribution', name: 'SIGHUP Distribution' },
  { slug: 'stackit-kubernetes-engine', name: 'STACKIT Kubernetes Engine SKE' },
  { slug: 'taikun', name: 'Taikun' },
  { slug: 'talos', name: 'Talos Linux' },
  { slug: 'tarook', name: 'Tarook' },
  { slug: 'tata-communications-vayu-kubernetes-service', name: 'Tata Communications Vayu Kubernetes Service' },
  { slug: 'typhoon', name: 'Typhoon' },
  { slug: 'vcluster', name: 'vCluster' },
  { slug: 'vmware-tanzu-kubernetes-grid', name: 'VMware Tanzu Kubernetes Grid' },
  { slug: 'volcengine-vke', name: 'Volcengine Kubernetes Engine' },
  { slug: 'elastisys-welkin-kubespray', name: 'Welkin based on Kubespray' },
  { slug: 'whitemist', name: 'Whitemist' },
  { slug: 'windrivercloud', name: 'Wind River Studio Cloud Platform' },
  { slug: 'wiit-wks', name: 'WKS - WIIT Kubernetes Service' },
]

const NAMES = [
  'Accordion',
  'AME',
  'Arcfra Kubernetes Engine',
  'Aruba Managed Kubernetes',
  'ASUS Cloud Infra',
  'Baidu Cloud Container Engine',
  'BKS',
  'BoCloud BeyondContainer',
  'Catalyst Cloud Kubernetes Service',
  'Cloud Container Distribution',
  'CoreWeave CKS',
  'kubeasz',
  'KubeSphere',
  'Leaseweb Managed Kubernetes',
  'Lenovo xCloud',
  'Linode Kubernetes Engine',
  'Nectar Magnum',
  'NestOS Kubernetes deployer',
  'NETWAYS Managed Kubernetes',
  'Oracle OKE',
  'OVHcloud Kubernetes',
  'Platform9 Managed Kubernetes',
  'plusserver PSKE',
  'Previder Kubernetes Engine',
  'Proact Managed Container Platform',
  'Red Hat OpenShift',
  'Red Hat OpenShift Dedicated',
  'Samsung SKE',
  'SECloudit',
  'StarlingX',
  'Swisscom Kubernetes Service',
  'Switch Cloud SCK',
  'TaiChu',
  'TECS OpenPalette',
  'Tencent Kubernetes Engine',
  'UpCloud Managed Kubernetes',
  'VIOLA',
  'VMware Tanzu Grid',
  'Vultr Kubernetes Engine',
]
</script>

<template>
  <div class="wall">
    <img
      v-for="l in LOGOS"
      :key="l.slug"
      class="mark"
      :src="asset(l.slug + '.png')"
      :alt="l.name"
    >
    <span v-for="n in NAMES" :key="n" class="distro">{{ n }}</span>
  </div>
</template>

<style scoped>
.wall {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: center;
  gap: .5rem .9rem;
  margin-top: 1rem;
}

.mark {
  height: 1.15rem;
  width: auto;
  max-width: 6.5rem;
  object-fit: contain;
}

/* Vendors with no usable logo URL still belong on the wall. */
.distro {
  font-size: .55rem;
  letter-spacing: .02em;
  opacity: .6;
  white-space: nowrap;
}
</style>
